lh_aw_grabrielle_alves:
  target: "{{ env_var('DEFAULT_TARGET') }}"
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('DEV_DBT_PROJECT') }}"
      dataset: "{{ env_var('DEV_DBT_DATASET') }}"
      keyfile: "{{ env_var('DEV_DBT_KEYFILE') }}"
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROD_DBT_PROJECT') }}"
      dataset: "{{ env_var('PROD_DBT_DATASET') }}"
      keyfile: "{{ env_var('PROD_DBT_KEYFILE') }}"